---

- name: add repo key 
  apt_key:
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    state: present

  # For Ubuntu 14.04 LTS, use this repository:
- name: add docker repo for Ubuntu 14.04
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
  when: ansible_distribution_version == '14.04'

  # For Ubuntu 16.04 lTS, use this repository:
- name: add docker repo for Ubuntu 16.04
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main'
  when: ansible_distribution_version == '16.04'

- name: install docker
  apt: name=docker-engine update_cache=yes  
