---

- name: epel release
  yum:
    name: epel-release
    state: latest
- name: add repo
  yum_repository:
    name: docker repo
    description: adding docker repo
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    gpgkey: https://download.docker.com/linux/ubuntu/gpg
    gpgcheck: yes

- name: installing the docker
  yum:
    name: docker-io
    state: latest
